### ISSUE TITLE
Pass script id with url to bypass the menu

### ISSUE THREAD

**Issue by MrWyss-MSFT** [MrWyss-MSFT/gist#1]
e.g. `iwr gist.ittips.ch/1 | iex` would directly call gist menu item 1. 
allows us to do  `iwr gist.ittips.ch/1 | iex | select Name`
not sure how to realize this yet or even possible, as `iwr` only downloads and the raw script is static.

**Comment by MrWyss-MSFT** [comment]
seems like it is possible:
The cloudflare redirect rule for test would be :

`(http.host eq "gist.ittips.ch" and starts_with(http.request.uri.path, "/test"))`

and luckily there is `$MyInvocation` variable which can be regexed to match uri path after / or /test/ or /dev/

```powershell
if ($($MyInvocation.MyCommand) -match 'gist\.ittips\.ch/(?:test/|dev/)?(\d+)') {
    $paramScriptNumber = $($matches[1])
    write-host "Scritp Number is $paramScriptNumber"
}
```

**Comment by MrWyss** [comment]
Fixed with latest commit
